services:
  backend:
    build: ./backend
    container_name: backend-challenge
    networks:
      - backend-bridge
      - frontend-bridge

  app-database:
    image: mysql:latest
    build:
      context: contextPath
      dockerfile: Dockerfile

networks:
  backend-bridge:
    driver: bridge

  frontend-bridge:
    driver: bridge
