services:
  backend:
    build: ./backend
    container_name: backend-challenge
    networks:
      - backend-bridge
      - frontend-bridge

networks:
  backend-bridge:
    driver: bridge

  frontend-bridge:
    driver: bridge
